### ISSUE TITLE
09 删除卡片

### ISSUE THREAD

**Issue by panmingzhi815** [panmingzhi815/DongluDoc#2]
请求海誉内容:
{"header":{"password":"test","sequeceid":"d64ee801338440ea90f49b62084c1012","key":"11232","username":"test"},"body":{"physicalCardId":2665}}

海誉响应内容:
{"header":{"message":"未知异常","status":"004"}}

**Comment by panmingzhi815** [comment]
如果该卡片在你那边不存在,你也可以返回为成功,因为这本身也已经表明两边的卡片都已经不存在了.

**Comment by huangyuzhi** [comment]
我这边已经写好，做删除的话都会判断的，这个不影响吧？
正式的数据不会出现这样的情况的
